forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /Tabulous

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /Tabulous

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /Tabulous

tablature:
    resource: "@TablatureBundle/Resources/config/routing.yml"
    prefix:   /Tabulous

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /Tabulous

