forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /Tabulous

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /Tabulous

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /Tabulous

tablature:
    resource: "@TablatureBundle/Resources/config/routing.yml"
    prefix:   /Tabulous

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /Tabulous

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resitting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile