tablature:
    path:     /
    defaults: { _controller: "TablatureBundle:Tablature:index" }

tablature_show:
    path:     /{id}/show
    defaults: { _controller: "TablatureBundle:Tablature:show" }

tablature_new:
    path:     /new
    defaults: { _controller: "TablatureBundle:Tablature:new" }

tablature_create:
    path:     /create
    defaults: { _controller: "TablatureBundle:Tablature:create" }
    requirements: { _method: post }

tablature_edit:
    path:     /{id}/edit
    defaults: { _controller: "TablatureBundle:Tablature:edit" }

tablature_update:
    path:     /{id}/update
    defaults: { _controller: "TablatureBundle:Tablature:update" }
    requirements: { _method: post|put }

tablature_delete:
    path:     /{id}/delete
    defaults: { _controller: "TablatureBundle:Tablature:delete" }
    requirements: { _method: post|delete }
