Artiste:
    type: entity
    table: artiste
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        nbtablature:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: nbTablature
    lifecycleCallbacks: {  }
