Commentaire:
    type: entity
    table: commentaire
    indexes:
        idMembre:
            columns:
                - idMembre
        idTablature:
            columns:
                - idTablature
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: date
            nullable: false
            comment: ''
        contenu:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        idtablature:
            targetEntity: Tablature
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idTablature:
                    referencedColumnName: id
            orphanRemoval: false
        idmembre:
            targetEntity: Membre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idMembre:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
